---
apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  annotations:
    agentBareMetal-agentSelector/autoSelect: "true"
  labels:
  name: glebe
  namespace: glebe
spec:
  baseDomain: rhpg.org
  clusterInstallRef:
    group: extensions.hive.openshift.io
    kind: AgentClusterInstall
    name: glebe
    version: v1beta1
  clusterName: glebe
  platform:
    agentBareMetal:
      agentSelector:
        matchLabels: {}
  pullSecretRef:
    name: pullsecret-cluster-glebe